#!/bin/bash

country=us

x=$(curl -s https://www.worldometers.info/coronavirus/country/$country/)

<<< "$x" grep -o -m 1  "<li\sclass=\"n.*" | sed -e 's/<[^>]*>//g' -e 's/&.*//g' | awk '{print "\033[32m" $1, $2, $3, "\033[38;5;7m" $4, "\033[38;5;3m" $5, $6, $7, "\033[38;5;33m" $8, $9, $10, $11, $12}'

<<< "$x" grep -oe "<span style=\"color:#aaa\">.*" -e "<span>[0-9].*" | sed  -e 's/<[^>]*>//g' | sed '1s/^/Coronavirus Cases: /' | sed '2s/^/Deaths: /' | sed '3s/^/Recovered: /' | sed '/^$/d' | tr '\n' ' ' | awk '{ gsub("Coronavirus Cases: ", "\033[1;33m&\033[0m");gsub("Deaths:", "\033[0;31m&\033[0m");gsub("Recovered:", "\033[1;36m&\033[0m"); print }'

# to print all info in  4 lines remove the \n from the tr option above and leave it like ~~> | tr ' ' ' ' |
